file(GLOB_RECURSE APPLICATION_SOURCES CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_SOURCE_DIR}/applications/*.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/applications/*.s"
    "${CMAKE_CURRENT_SOURCE_DIR}/applications/*.S")
list(APPEND FIRMWARE_SOURCES ${APPLICATION_SOURCES})

