file(GLOB_RECURSE BOARD_DRIVER_SOURCES CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_SOURCE_DIR}/drivers/*.c"
    "${CMAKE_CURRENT_SOURCE_DIR}/drivers/*.s"
    "${CMAKE_CURRENT_SOURCE_DIR}/drivers/*.S")
list(APPEND FIRMWARE_SOURCES ${BOARD_DRIVER_SOURCES})

