#!/usr/bin/env python3
"""Generate the compact 16 px UI font and 32 px weather-status font."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


def collect_characters(module_root: Path) -> list[str]:
    text = ""
    for pattern in ("*.c", "*.h"):
        for path in module_root.rglob(pattern):
            if path.name == "lvww_font_cjk_16.c":
                continue
            text += path.read_text(encoding="utf-8")
    characters = set(re.findall(r"[\u2103\u3000-\u9fff\uff00-\uffef]", text))
    # Keep Latin text, digits and punctuation on the same SimSun baseline as
    # Chinese instead of mixing metrics from LV_FONT_DEFAULT.
    characters.update(chr(codepoint) for codepoint in range(0x20, 0x7F))
    return sorted(characters, key=ord)


def render_glyph(font: ImageFont.FreeTypeFont, char: str, pixel_size: int) -> list[int]:
    image = Image.new("L", (pixel_size, pixel_size), 0)
    draw = ImageDraw.Draw(image)
    # Keep every glyph on the font's shared baseline.  Cropping each glyph to
    # its own bounding-box top makes low horizontal strokes such as "一" jump
    # to the top of the line.
    draw.text((0, 0), char, font=font, fill=255)

    packed: list[int] = []
    for y in range(pixel_size):
        for x in range(0, pixel_size, 2):
            high = min(15, (image.getpixel((x, y)) + 8) // 17)
            low = min(15, (image.getpixel((x + 1, y)) + 8) // 17)
            packed.append((high << 4) | low)
    return packed


def format_values(values: list[int], width: int = 12) -> str:
    lines = []
    for start in range(0, len(values), width):
        chunk = values[start : start + width]
        lines.append("        " + ", ".join(f"0x{value:02x}" for value in chunk))
    return ",\n".join(lines)


def generate(module_root: Path, font_path: Path, output: Path) -> None:
    characters = collect_characters(module_root)
    weather_characters = sorted(set("℃晴间云多雾毛雨有雪雷暴"), key=ord)
    if not characters:
        raise RuntimeError("no CJK characters found")

    font = ImageFont.truetype(str(font_path), 16)
    codepoints = ", ".join(f"0x{ord(char):04x}u" for char in characters)
    advance_widths = format_values([
        max(1, min(16, int(round(font.getlength(char)))))
        for char in characters
    ])
    glyphs = []
    for char in characters:
        values = format_values(render_glyph(font, char, 16))
        glyphs.append(f"    /* U+{ord(char):04X} {char} */\n    {{\n{values}\n    }}")

    weather_font = ImageFont.truetype(str(font_path), 32)
    weather_codepoints = ", ".join(
        f"0x{ord(char):04x}u" for char in weather_characters
    )
    weather_glyphs = []
    for char in weather_characters:
        values = format_values(render_glyph(weather_font, char, 32))
        weather_glyphs.append(
            f"    /* U+{ord(char):04X} {char} */\n    {{\n{values}\n    }}"
        )

    source = f"""/*
 * Generated by tools/generate_font.py. Do not edit manually.
 * Font: {font_path.name}, 16 px, 4 bpp
 * Characters ({len(characters)}): {''.join(characters)}
 */

#include "lv_wifi_weather.h"

#define LVWW_FONT_GLYPH_BYTES 128u

static const uint32_t lvww_codepoints[] =
{{
    {codepoints}
}};

static const uint8_t lvww_advance_widths[] =
{{
{advance_widths}
}};

static const uint8_t lvww_glyph_bitmap[][LVWW_FONT_GLYPH_BYTES] =
{{
{",\n".join(glyphs)}
}};

static int lvww_font_find(uint32_t codepoint)
{{
    int low = 0;
    int high = (int)(sizeof(lvww_codepoints) / sizeof(lvww_codepoints[0])) - 1;

    while (low <= high)
    {{
        int middle = low + (high - low) / 2;
        if (lvww_codepoints[middle] == codepoint) return middle;
        if (lvww_codepoints[middle] < codepoint) low = middle + 1;
        else high = middle - 1;
    }}
    return -1;
}}

static bool lvww_font_get_glyph_dsc(const lv_font_t *font,
                                    lv_font_glyph_dsc_t *dsc,
                                    uint32_t letter,
                                    uint32_t letter_next)
{{
    int index;
    (void)font;
    (void)letter_next;
    index = lvww_font_find(letter);
    if (index < 0) return false;

    /* Custom get_glyph_dsc callbacks return the final width in pixels. */
    dsc->adv_w = lvww_advance_widths[index];
    dsc->box_w = 16;
    dsc->box_h = 16;
    dsc->ofs_x = 0;
    dsc->ofs_y = -2;
    dsc->bpp = 4;
    dsc->is_placeholder = 0;
    return true;
}}

static const uint8_t *lvww_font_get_bitmap(const lv_font_t *font,
                                           uint32_t letter)
{{
    int index;
    (void)font;
    index = lvww_font_find(letter);
    return index >= 0 ? lvww_glyph_bitmap[index] : NULL;
}}

const lv_font_t lvww_font_cjk_16 =
{{
    .get_glyph_dsc = lvww_font_get_glyph_dsc,
    .get_glyph_bitmap = lvww_font_get_bitmap,
    .line_height = 19,
    .base_line = 3,
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = -2,
    .underline_thickness = 1,
    .dsc = NULL,
    .fallback = LV_FONT_DEFAULT
}};

#define LVWW_FONT_LARGE_GLYPH_BYTES 512u

static const uint32_t lvww_large_codepoints[] =
{{
    {weather_codepoints}
}};

static const uint8_t lvww_large_glyph_bitmap[][LVWW_FONT_LARGE_GLYPH_BYTES] =
{{
{",\n".join(weather_glyphs)}
}};

static int lvww_large_font_find(uint32_t codepoint)
{{
    int low = 0;
    int high = (int)(sizeof(lvww_large_codepoints) /
                     sizeof(lvww_large_codepoints[0])) - 1;

    while (low <= high)
    {{
        int middle = low + (high - low) / 2;
        if (lvww_large_codepoints[middle] == codepoint) return middle;
        if (lvww_large_codepoints[middle] < codepoint) low = middle + 1;
        else high = middle - 1;
    }}
    return -1;
}}

static bool lvww_large_font_get_glyph_dsc(const lv_font_t *font,
                                          lv_font_glyph_dsc_t *dsc,
                                          uint32_t letter,
                                          uint32_t letter_next)
{{
    (void)font;
    (void)letter_next;
    if (lvww_large_font_find(letter) < 0) return false;

    dsc->adv_w = 32;
    dsc->box_w = 32;
    dsc->box_h = 32;
    dsc->ofs_x = 0;
    dsc->ofs_y = -4;
    dsc->bpp = 4;
    dsc->is_placeholder = 0;
    return true;
}}

static const uint8_t *lvww_large_font_get_bitmap(const lv_font_t *font,
                                                 uint32_t letter)
{{
    int index;
    (void)font;
    index = lvww_large_font_find(letter);
    return index >= 0 ? lvww_large_glyph_bitmap[index] : NULL;
}}

const lv_font_t lvww_font_cjk_32 =
{{
    .get_glyph_dsc = lvww_large_font_get_glyph_dsc,
    .get_glyph_bitmap = lvww_large_font_get_bitmap,
    .line_height = 37,
    .base_line = 5,
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = -3,
    .underline_thickness = 2,
    .dsc = NULL,
    .fallback = &lvww_font_cjk_16
}};
"""
    output.write_text(source, encoding="utf-8", newline="\n")
    print(
        f"generated {output} with {len(characters)} UI glyphs and "
        f"{len(weather_characters)} large weather glyphs"
    )


def main() -> None:
    script_dir = Path(__file__).resolve().parent
    module_root = script_dir.parent
    parser = argparse.ArgumentParser()
    parser.add_argument("--font", type=Path, default=Path(r"C:\Windows\Fonts\simsun.ttc"))
    parser.add_argument("--output", type=Path,
                        default=module_root / "src" / "lvww_font_cjk_16.c")
    args = parser.parse_args()
    generate(module_root, args.font, args.output)


if __name__ == "__main__":
    main()
