#!/usr/bin/env python3
"""Generate the compact 16 px Chinese font used by lv_wifi_weather."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


def collect_characters(module_root: Path) -> list[str]:
    text = ""
    for pattern in ("*.c", "*.h"):
        for path in module_root.rglob(pattern):
            if path.name == "lvww_font_cjk_16.c":
                continue
            text += path.read_text(encoding="utf-8")
    return sorted(set(re.findall(r"[\u3000-\u9fff]", text)), key=ord)


def render_glyph(font: ImageFont.FreeTypeFont, char: str) -> list[int]:
    image = Image.new("L", (16, 16), 0)
    draw = ImageDraw.Draw(image)
    bbox = draw.textbbox((0, 0), char, font=font)
    draw.text((-bbox[0], -bbox[1]), char, font=font, fill=255)

    packed: list[int] = []
    for y in range(16):
        for byte_x in range(2):
            value = 0
            for bit in range(8):
                x = byte_x * 8 + bit
                if image.getpixel((x, y)) >= 96:
                    value |= 0x80 >> bit
            packed.append(value)
    return packed


def format_values(values: list[int], width: int = 12) -> str:
    lines = []
    for start in range(0, len(values), width):
        chunk = values[start : start + width]
        lines.append("        " + ", ".join(f"0x{value:02x}" for value in chunk))
    return ",\n".join(lines)


def generate(module_root: Path, font_path: Path, output: Path) -> None:
    characters = collect_characters(module_root)
    if not characters:
        raise RuntimeError("no CJK characters found")

    font = ImageFont.truetype(str(font_path), 16)
    codepoints = ", ".join(f"0x{ord(char):04x}u" for char in characters)
    glyphs = []
    for char in characters:
        values = format_values(render_glyph(font, char))
        glyphs.append(f"    /* U+{ord(char):04X} {char} */\n    {{\n{values}\n    }}")

    source = f"""/*
 * Generated by tools/generate_font.py. Do not edit manually.
 * Font: {font_path.name}, 16 px, 1 bpp
 * Characters ({len(characters)}): {''.join(characters)}
 */

#include "lv_wifi_weather.h"

extern const lv_font_t lv_font_simsun_16_cjk;

#define LVWW_FONT_GLYPH_BYTES 32u

static const uint32_t lvww_codepoints[] =
{{
    {codepoints}
}};

static const uint8_t lvww_glyph_bitmap[][LVWW_FONT_GLYPH_BYTES] =
{{
{",\n".join(glyphs)}
}};

static int lvww_font_find(uint32_t codepoint)
{{
    int low = 0;
    int high = (int)(sizeof(lvww_codepoints) / sizeof(lvww_codepoints[0])) - 1;

    while (low <= high)
    {{
        int middle = low + (high - low) / 2;
        if (lvww_codepoints[middle] == codepoint) return middle;
        if (lvww_codepoints[middle] < codepoint) low = middle + 1;
        else high = middle - 1;
    }}
    return -1;
}}

static bool lvww_font_get_glyph_dsc(const lv_font_t *font,
                                    lv_font_glyph_dsc_t *dsc,
                                    uint32_t letter,
                                    uint32_t letter_next)
{{
    (void)font;
    (void)letter_next;
    if (lvww_font_find(letter) < 0) return false;

    dsc->adv_w = 16;
    dsc->box_w = 16;
    dsc->box_h = 16;
    dsc->ofs_x = 0;
    dsc->ofs_y = -2;
    dsc->bpp = 1;
    dsc->is_placeholder = 0;
    return true;
}}

static const uint8_t *lvww_font_get_bitmap(const lv_font_t *font,
                                           uint32_t letter)
{{
    int index;
    (void)font;
    index = lvww_font_find(letter);
    return index >= 0 ? lvww_glyph_bitmap[index] : NULL;
}}

const lv_font_t lvww_font_cjk_16 =
{{
    .get_glyph_dsc = lvww_font_get_glyph_dsc,
    .get_glyph_bitmap = lvww_font_get_bitmap,
    .line_height = 19,
    .base_line = 3,
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = -2,
    .underline_thickness = 1,
    .dsc = NULL,
    .fallback = &lv_font_simsun_16_cjk
}};
"""
    output.write_text(source, encoding="utf-8", newline="\n")
    print(f"generated {output} with {len(characters)} CJK glyphs")


def main() -> None:
    script_dir = Path(__file__).resolve().parent
    module_root = script_dir.parent
    parser = argparse.ArgumentParser()
    parser.add_argument("--font", type=Path, default=Path(r"C:\Windows\Fonts\simsun.ttc"))
    parser.add_argument("--output", type=Path,
                        default=module_root / "src" / "lvww_font_cjk_16.c")
    args = parser.parse_args()
    generate(module_root, args.font, args.output)


if __name__ == "__main__":
    main()
