#!/usr/bin/env python3
"""Generate the APP-side ECDSA P-256 key material for H743 OTA signing."""

from __future__ import annotations

import argparse
import hashlib
import os
import pathlib

try:
    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives.asymmetric import ec
except ImportError as error:
    raise SystemExit(
        "The 'cryptography' package is required: python -m pip install cryptography"
    ) from error


def parse_args() -> argparse.Namespace:
    project = pathlib.Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--private-key",
        type=pathlib.Path,
        default=project / "tools/keys/ota_signing_private.pem",
        help="private PEM path; existing keys are reused",
    )
    parser.add_argument(
        "--app-header",
        type=pathlib.Path,
        default=project / "applications/ota/ota_trusted_key.h",
        help="APP public-key header output path",
    )
    parser.add_argument(
        "--password-env",
        help="environment variable containing the PEM password",
    )
    parser.add_argument(
        "--force-new-key",
        action="store_true",
        help="replace an existing private key (key rotation)",
    )
    return parser.parse_args()


def password_from_environment(name: str | None) -> bytes | None:
    if not name:
        return None
    value = os.environ.get(name)
    if value is None:
        raise SystemExit(f"password environment variable is not set: {name}")
    return value.encode("utf-8")


def load_or_generate_private_key(
    path: pathlib.Path,
    password: bytes | None,
    force_new_key: bool,
) -> ec.EllipticCurvePrivateKey:
    if path.exists() and not force_new_key:
        key = serialization.load_pem_private_key(path.read_bytes(), password=password)
        if not isinstance(key, ec.EllipticCurvePrivateKey) or not isinstance(
            key.curve, ec.SECP256R1
        ):
            raise SystemExit("the OTA private key must use ECDSA P-256 (secp256r1)")
        return key

    key = ec.generate_private_key(ec.SECP256R1())
    encryption = (
        serialization.BestAvailableEncryption(password)
        if password
        else serialization.NoEncryption()
    )
    encoded = key.private_bytes(
        serialization.Encoding.PEM,
        serialization.PrivateFormat.PKCS8,
        encryption,
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(encoded)
    return key


def raw_public_key(key: ec.EllipticCurvePrivateKey) -> bytes:
    numbers = key.public_key().public_numbers()
    return numbers.x.to_bytes(32, "big") + numbers.y.to_bytes(32, "big")


def render_header(public_key: bytes) -> str:
    fingerprint = hashlib.sha256(public_key).hexdigest()
    rows = []
    for offset in range(0, len(public_key), 8):
        values = ", ".join(f"0x{value:02X}" for value in public_key[offset : offset + 8])
        rows.append(f"    {values},")
    return (
        "#ifndef OTA_TRUSTED_KEY_H\n"
        "#define OTA_TRUSTED_KEY_H\n\n"
        "#include <stdint.h>\n\n"
        "/* Generated by tools/ota_signing_key.py. Public key only. */\n"
        f"/* SHA-256 fingerprint: {fingerprint} */\n"
        "static const uint8_t ota_trusted_public_key[64] =\n"
        "{\n"
        + "\n".join(rows)
        + "\n};\n\n"
        "#endif\n"
    )


def write_header(path: pathlib.Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def main() -> int:
    args = parse_args()
    password = password_from_environment(args.password_env)
    key = load_or_generate_private_key(
        args.private_key, password, args.force_new_key
    )
    public_key = raw_public_key(key)
    header = render_header(public_key)
    write_header(args.app_header, header)
    print(f"Private key: {args.private_key}")
    print(f"APP public key: {args.app_header}")
    print(
        "Copy the APP public-key header to the Bootloader project manually "
        "when you are ready to update its trust key."
    )
    print(f"Public key SHA-256: {hashlib.sha256(public_key).hexdigest()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
